
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: 3344
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: todo_development

test:
  <<: *default
  database: todo_test

production:
  <<: *default
  database: todo_production
  username: excavator
  password: <%= ENV['TODO_DATABASE_PASSWORD'] %>
